displayName: AllowIPRequest
type: middleware
iconPath: .assets/icon.png

import: github.com/CAJIO/allowiprequest

summary: 'Its plugin that allows you to whitelist your ip address by visiting a secret URL. It protects your services by blocking all requests by default while allowing users to self-whitelist their IP address by visiting a secret URL.'

testData:
  KnockURL: "/knock-knock"
  WhitelistDuration: "5s"
  AllowedSubnets:
    - "192.168.0.0/16"
    - "10.0.0.0/8"
    - "127.0.0.0/8"
  SyncAllowlist: true
  AllowlistFile: "/etc/traefik/conf.d/allowlist.yml"
